spring:
  application:
    name: yhyy-zuul
  datasource:                           # Mabtis数据源，用于主库操作
    druid:
      url: jdbc:mysql://192.168.1.175:3306/0903-test
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      initial-size: 20
      max-active: 100
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 'x'
      filters: stat,slf4j
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb
  redis:
    host: 192.168.1.129
    password: redismima
    port: 6379
    database: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8669/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
zuul:
  routes:
    yhyy-bs-acc: /acc/**
    yhyy-bs-cod: /cod/**
    yhyy-bs-mda: /mda/**
    yhyy-bs-odr: /odr/**
    yhyy-bs-rpo: /rpo/**
    yhyy-bs-sca: /sca/**
    yhyy-bs-usr: /usr/**
    yhyy-solr: /solr/**
    spring-cloud-producer: /spring-cloud-producer/**
    yhyy-front-admin-2.0: /admin2.0/**
    yhyy-front-admin: /admin/**

  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 30000              #请求处理的超时时间
  ConnectTimeout: 30000           #ribbon请求连接的超时时间
  MaxAutoRetries: 3               #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1    #对下个实例的重试次数
  MaxConnectionsPerHost: 1500    #最大连接数
  MaxTotalConnections: 1000      #最大活动连接数

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000

server:
  port: 8060
  tomcat:
    max-threads: 3000
mq:
  suffix: _178
  url: http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet
  accessKey: LTAIp2gpRJI0gvKu
  secretKey: AfhWdaEw5zrIx9d08Z5058J4QCYEnv

#各端是否启动header
pcHeader: 0
h5Header: 0
androidHeader: 0
iosHeader: 0

zFilterCheck: 1
zFilterContent: u/logOut,u/login,u/getTempToken,u/getSaltRand,u/register,u/loginByVercode,u/loginOfterCkeck,operateCenter/getOperates,operateCenter/getOperateByOperateUsername,u/getUsersByUsernameLeft,operateCenter/getNearOperateCenterCount,operateCenter/getNearOperateCenterForPage,u/getNearAssistForPage,u/checkUserByUsername,u/weChatBindingOldUser,u/getAssist,u/weChatLogin,u/weChatBinding,u/weChatBindingLogin,u/checkVeriCode,u/checkUserMobile,product/listCategory23,product/category,product/listPrductEvaluation,product/getPrductDetail,product/listPropByProductItemList,product/getProductPriceByPorp,product/listPropValueByPropId,product/listProductBrand,product/getChildCategory,product/getVipProductByNo,product/getVipProduct,product/getEvaluationBySupplierId,product/getUpCategory,product/listSupplierProductCategory,area/getProvince,area/getCity,area/getAreaByCode,usr/getShopShareUrl,address/getStoreSelfReceiveAddress,operateCenter/selectAgreementByName,sendCode/sendCode,oauth/openweixin/wechat_oauth,oauth/openweixin/wechat_web,oauth/openweixin/receive_ticket,oauth/openweixin/receive_ticket_web,home/listNotice,advert/listAdvertCat,feignSolr/guessUserLike,product/getProductStoreUserSales,feignSolr/queryProductList,feignSolr/querySolrMerchant,feignSolr/queryHotWords,feignSolr/querySolrSuggest,staffEntrance/login,im/message/copy,putBlock,oauth/openweixin/wechat_web_binding,oauth/openweixin/receive_ticket_web_binding,app/version/queryNewestVersionInfo,u/getCustomQRCode,menu/listMenu,advert/getAdvertCat,oauth/openweixin/wechat_binding,oauth/openweixin/receive_ticket_binding,home/getNotice,oauth/openweixin/getTicket,help/queryHelpCoreCategory,help/queryHelpDescById,product/getProductDetail,common/isShow,common/iosVersion,test/testHeaderToken,storeUser/loadCustomerServiceTel,usr/getCkeckCode,usr/subCkeckCode
updateSwitch: 1 #1开始使用升级功能 0关闭