server:
  port: 8200

spring:
  application:
    name: yhyy-admin-es
  http:
    multipart:
      maxFileSize: 10Mb

elasticsearchhost: 192.168.1.192
elasticsearchport: 9300

eureka:
  instance:
    prefer-ip-address: true
# ES配置
es:
  client:
    transport:
      sniff: false
  cluster:
    name: yhyy-admin
  ignore:
    cluster:
      name: false
  ip: 192.168.1.192:9300 # es的ip及端口号，多个以逗号分隔
  routing:
    time: 5s
  nodes:
    interval: 5s

  index_name: test-index

config: 123

