server:
  port: 8200

spring:
  application:
    name: yhyy-admin-es
  http:
    multipart:
      maxFileSize: 10Mb
elasticsearchhost: 192.168.1.192
elasticsearchport: 9200

# ES配置
es:
  client:
    transport:
      sniff: true
  cluster:
    name: yhyy-admin
  ignore:
    cluster:
      name: false
  ip: 106.15.197.39:9300,106.14.146.115:9300,106.14.146.115:9300 # es的ip及端口号，多个以逗号分隔
  routing:
    time: 5s
  nodes:
    interval: 5s

  index_name: test-index