spring:
  application:
    name: yhyy-solr
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  datasource:
    druid:
      url: jdbc:mysql://rm-uf66cmggonxd2i684.mysql.rds.aliyuncs.com:3306/drds_bj_scph1230_cmiq_0000
      driver-class-name: com.mysql.jdbc.Driver
      username: drds_bj_scph1230
      password: dWkSfAIW53CJRLUy
      #url: jdbc:mysql://drds42g89fs73g0z.drds.aliyuncs.com:3306/drds_bj_scyhyh20180130
      #driver-class-name: com.mysql.jdbc.Driver
      #username: drds_bj_scyhyh20180130
      #password: hFeAiWfv2X8nGu4Z
      initialSize: 20
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      filters: stat,slf4j
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  redis:
    host: r-uf66d90bd02919f4.redis.rds.aliyuncs.com
    password: JY3J0V7p0bJxp4UB
    port: 6379
    database: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  zipkin:
    base-url: http://172.19.173.98:9666
  sleuth:
    sampler:
      percentage: 1

management:
  security:
    enabled: false

logging:
  level:
    root:  WARN
    com:
      yhyy:
        solr:
          controller: INFO
          MQActivity: INFO
          es:
            service: INFO
            dao: INFO

#service discovery url
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://172.19.173.98:8669/eureka/
  instance:
    hostname: web-12   # 指定该Eureka实例的主机名
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
server:
  port: 9999
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 60000
  
mybatis:
  check-config-location: true                          #配置校验（true/false）
  config-location: classpath:mybatis-config.xml         #mybatis配置文件
  mapper-locations: classpath*:mapper/readXml/*.xml
elasticsearch.cluster.name: yhyy
elasticsearch.server.arr: 172.19.173.98:9300,172.19.173.98:9301,172.19.173.98:9302
indexName: collection
MerchantTypeName: Merchant
ProductTypeName: Product
footIndexName: footcollection
footTypeName: foot
historyIndexName: historycollection
historyTypeName: history
ONSAddr: http://onsaddr-internal.aliyun.com:8080/rocketmq/nsaddr4client-internal
topicName: yhyy-search_wn
accessKey: LTAIp2gpRJI0gvKu
secretKey: AfhWdaEw5zrIx9d08Z5058J4QCYEnv
consumerId: CID_SOLRINDEX_wn
#1是 可以看不到会员商品 2是查出会员商品
isShow: 2
esUrl: http://172.19.173.98:9200
#1是 屏蔽悦超市 2是放开悦超市
isShowMda: 1