server:
  port: 8888
spring:
  application:
    name: yhyy-yuepay
  datasource:
    druid:
      url: jdbc:mysql://drdsd267745t4p0r.drds.aliyuncs.com:3306/drds_bj_scph1230
      driver-class-name: com.mysql.jdbc.Driver
      username: drds_bj_scph1230
      password: rmuZHgoF3J6XeZvB
      initial-size: 20  #初始化连接数
      max-active: 100  #最大连接池数量
      min-idle: 5  #最小连接池数量
      max-wait: 60000  #获取连接时最大等待时间
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000  #连接保持空闲而不被驱逐的最小时间
      validation-query: SELECT 'x'  #用来检测连接是否有效的SQL
      filters: stat,slf4j
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:  #关闭监控页面
        enabled: false
      web-stat-filter:  #关闭采集数据功能
        enabled: false
  redis:
    host: r-uf61405c450dbc44.redis.rds.aliyuncs.com
    password: S6PRNhepnmNY3Msr
    port: 6379
    database: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

mybatis:
  check-config-location: true                          #配置校验（true/false）
  config-location: classpath:mybatis-config.xml         #mybatis配置文件
  mapper-locations: classpath*:mapper/**/*.xml    #mapper xml配置路径

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://172.19.173.76:8669/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true

#易宝一键支付
yeepay:
  #商户编号
  merchantAccount: 10015335357
  #易宝公玥
  yeepayPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDGUtCSiR9knXLBBcVw72CKnoo/iM0WCuW/Qzf3NMW+eSQamHXuKBaQBF3cbYI9oq5RFOxMiB2siwC5UXrPd+gz/y0bd2R0tfI8BK0gYhvMPZSeB67H3BOrIiiGrItIosTFNn15bz0Y23bUj5G3LX2EjWGFPH+fmjWUGxeZOZTbywIDAQAB
  #商户私钥
  merchantPrivateKey: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAK5GzGXRTdeaslbWMVfIyPawOHyRI6yV7Pqn5iAklicO2H94+1bqwQrx3GpUXWBwRryBrX5Phy547JAF/xpRUTOUhOiMdh50phnBAfGqT9ySoiBL9n9Sh1Yb64RMCqXBk/JSr7O3vfdh812mK5WPE57J6kwWNNdYBDvPGY3lmMTBAgMBAAECgYByp4lZgvXfXprtnkUgJ6xu/0hqS2JY7NnXnhY8F1XhpFaypnlUmWUfOjd0jMRR6gvfgMEPVGrvHAcmSYunWNA+NErapcL5iuzAq0IU00wm9u02ayq+GD2oWbEihJHODRoQ/sIRj2870eBm1FfUTsK+sqBc/SMM8tKlL3DNlYCOsQJBAON9wiqzGEP4mFrmBs5dt0irRBABCOGhRvN1d50JAK0e6BkSMcUo6a2EVFSXFjT6piBJ8qN1GNXc05vMCaeQHrcCQQDEHdZdZ+x7QzQRtZo4WdMARHFz1d4prJrPrNzvrOnXog6pUQf1kexIOlrfEOtTySOqXkF5x1sCT4tWfQKgIcBHAkBuj5ENRYtWhXwuOTs3km5gX/QtPwN8/O/JpN5kMJrmiG3OuXv80Tx4eyatEdzWFLcmXCoTbPaMAc3KGyjaCf4TAkAXAxFGQI2FISuY8GA6QH/7xgwx9WRuK2y29aevD/EYdlGWGIYAkLDTANXs2sViPXXL5ed07KmHKeJFscF/HLa9AkA9iKWgOvTeTI6U8bWsAdaHuoRaUPFcAaIlqvwveIEaN5XhE9kiS+YArcoMQYtOg3Qwj3+SOzYRD0yvoIBxOsnh
  #订单支付接口请求地址 h5 ios android
  PayApi: https://ok.yeepay.com/paymobile/api/pay/request
  #订单支付接口请求地址 PC
  PayPCApi: https://ok.yeepay.com/payweb/api/pay/request
  #订单退款接口
  RefundPayApi: https://ok.yeepay.com/merchant/query_server/direct_refund
  #退款查询接口
  RefundSearchPayApi: https://ok.yeepay.com/merchant/query_server/refund_single
  #订单查询接口
  OrderSearchPayApi: https://ok.yeepay.com/merchant/query_server/pay_single
  #后台回调地址
  callbackurl: http://101.132.158.152:8888/yeepay/callbackApi
  #前台pc回调地址
  pccallbackurl: https://testwww.yuehuayueyou.com
  #前台h5回调地址
  h5callbackurl: https://testtm.yuehuayueyou.com
  #前台android,ios回调地址
  fcallbackurl: https://m.yuehuayueyou.com/store
  #用户前缀，1：生产，2：测试  生产的不加前缀
  prefixUser: 2

  #代付代发的商户编号，和支付的商户编号相同
  merId: 10015335357
  #证书密码，程序中用
  pfxPrivateKey: 335357
  #代付代发的商户密钥
  hmacKey: 102kwyw8kj15jmyewkh5fhqqi9vzis9r4wdhyicdkwplddnd41ltfxgcqlof
  #代付代发的打款地址
  onlinePaymentReqURL: https://cha.yeepay.com/app-merchant-proxy/groupTransferController.action

#易宝2支付
yeepay2:
  #商户编号
  merchantAccount: 10014988743
  #商户私钥
  merchantPrivateKey: 6qhT0Zm1K571TJ6ut1BuPw85HG8928XZ2ifH53sid7WU1gysNbQ03hK33E53
  #订单支付接口请求地址
  PayApi: https://o2o.yeepay.com/zgt-api/api/pay
  #订单退款接口请求地址
  RefundPayApi: https://o2o.yeepay.com/zgt-api/api/refund
  #后台回调地址
  callbackurl: http://101.132.158.152:8888/yeepay2/callbackApi
  #前台pc回调地址
  pccallbackurl: https://testwww.yuehuayueyou.com
  #前台h5回调地址
  h5callbackurl: https://testtm.yuehuayueyou.com
  #前台android,ios回调地址
  fcallbackurl: https://m.yuehuayueyou.com/store
  #移动支付页签
  appstatement: https://www.yuehuayueyou.com
  #appName
  appname: yhyy
  #用户前缀，1：生产，2：测试
  prefixUser: 2

#开联通
ops:
  #单笔代付地址
  singlePayUrl: https://pg.openepay.com/gateway/singleagentpay
  #商户号
  mchtId: 101000170608001
  #代付查询接口
  singPayQueryUrl: https://query.openepay.com/mchtoq/agentPaySingleQuery
  #商户私钥密码
  merchantPrivateCertificatePassword : 308751
  #前台pc回调地址
  pccallbackurl: https://testwww.yuehuayueyou.com
  #前台h5回调地址
  h5callbackurl: https://testtm.yuehuayueyou.com
  #前台android,ios回调地址
  fcallbackurl: https://m.yuehuayueyou.com/store
  #退款请求地址
  refundApiUrl: https://pg.openepay.com/gateway/index.do
  #支付回调地址
  ReceiveUrl: http://101.132.158.152:8888/kltpay/callbackApi
  #支付请求地址
  payApiUrl: https://pg.openepay.com/gateway/index.do
  #app支付请求地址
  appPayApiUrl: https://mobile.openepay.com/mobilepay/index.do
  merchantKey: 6qhT0Zfnskdgj58ut1BuPw85Hsahysc66fhsk5ifH53sid7YUW
#爱农
chinagpay:
  #商户号
  merId : 929000095023657
  #商户私钥密码
  merKey : 3emESfuRZymp3UPWeEpuYSkNEzRskDN7
  #下行订单支付、查询接口请求地址
  chinaGpayUrl : http://pay.chinagpay.com/bas/BgTrans

  #支付地址
  payApiUrl: http://gpay.chinagpay.com/bas/FrontTrans
  #回调地址
  backUrl: https://typ.yuehuayueyou.com/chinagpay/callbackApi
  #退款地址
  refundApiUrl: http://gpay.chinagpay.com/bas/BgTrans
  #前台pc回调地址
  pccallbackurl: https://testwww.yuehuayueyou.com
  #前台h5回调地址
  h5callbackurl: https://testtm.yuehuayueyou.com
  #前台android,ios回调地址
  fcallbackurl: https://m.yuehuayueyou.com/store
#易宝3
yeepayyop:
  #商户号
  customerNumber : 10020715445
  groupNumber: 10020715445
  #父商编
  parentMerchantNo: 10020715445
  #子商编
  merchantNo: 10020715445
  #基地址
  baseUri: https://open.yeepay.com/yop-center
  #出款地址
  paymentUri: /rest/v1.0/balance/transfer_send
  #查询地址
  paymentqueryUri: /rest/v1.0/balance/transfer_query
  #订单创建URI
  tradeOrderURI: /rest/v1.0/std/trade/order
  #YOP单笔退款URI
  refundURI: /rest/v1.0/std/trade/refund
  #标准收银台
  chashierUrl: https://cash.yeepay.com/cashier/std
  #前台pc回调地址
  pccallbackurl: https://testwww.yuehuayueyou.com
  #前台h5回调地址
  h5callbackurl: https://testtm.yuehuayueyou.com
  #前台android,ios回调地址
  fcallbackurl: https://m.yuehuayueyou.com/store
  #退款请求地址
  refundApiUrl: https://pg.openepay.com/gateway/index.do
  #用户前缀，1：生产，2：测试  生产的不加前缀
  prefixUser: 2
  #后台回调地址
  callbackurl: http://101.132.158.152:8888/yeepay3/callbackApi

#快钱支付
kqpay:
  cipher: 123123
  merchantAcctId: 1020993241301
  bgUrl: https://typ.yuehuayueyou.com/kuaiqian/callbackApi
  kqUrl: https://www.99bill.com/gateway/recvMerchantInfoAction.htm
  kqMobileUrl: https://www.99bill.com/mobilegateway/recvMerchantInfoAction.htm
  fail: https://testwww.yuehuayueyou.com/fail/
  refund:
    key: QE3DJ6B99IU8Z769
    merchantId: 10209932413
    version: bill_drawback_api_1
    url: https://www.99bill.com/webapp/receiveDrawbackAction.do
    commandType: C001

pay:
  #前台pc回调地址
  pccallbackurl: https://testwww.yuehuayueyou.com
  #前台h5回调地址
  h5callbackurl: https://testtm.yuehuayueyou.com
  #前台android,ios回调地址
  fcallbackurl: https://m.yuehuayueyou.com/store
  #用户前缀，生产不加，测试加T
  prefixUser: T

#商银信
allscorepay:
  #支付地址
  payRequest: https://paymenta.allscore.com/olgateway/uion/unionTknOpenCardAndPay.htm
  #支付地址
  payRequestProUrl: https://paymenta.allscore.com/olgateway
  #商户编号
  merchantId: "001018041304657"
  #通知URL
  notifyUrl: https://typ.yuehuayueyou.com/allscorepay/notify
  #字符
  charSet: UTF-8
  #支付方式
  payMethod: uionOrderAndPay
  #公匙
  AllscorePublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCK7Uy5ZWqS6cDVzkzZWatBo+M0fYJtSpgONiYL5iX8eXTA8o5qHgkaLMnYHBSsxA6AaMRxpgtHVUCSVHVFTKVZ179/zRODxTitrm/BPRFzTaiUa6cYWkAn1jy0zaHlRQDkPfdfUH8bGqenMYaGluRMu+F5f1qrJCQncAfBjdy7GQIDAQAB
  #私匙
  MerchantPrivateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAMz0+jLs4jVnGnLpJFVJz3AiPEHa4nIQc2jM5MBb4dz2nh8cs/wtb3H/Vppfoi6esZ0FQtKIox8Bi95DnTmp4ToKB7NSsszHtEdbYAhkUk6EiOdiYjsZZBbDth7tgN6jD5plorcbTsRW4Ky+0mp3Az8bymAcKsWtTcdsAVX7WpI7AgMBAAECgYEAysFatoBTM+NAbgcoE1uGY/bqR3fC5nZRxY5UidsbsJ0kRcD+aO2Fv2+K/AK5jYceTCjFN0NGo8jC1mlrI31kOV/0LhN4SjPdrbaW8F4TL4zuPRzIaeRu0qH/rVGZYZdEZxfwhjOyKorYhRipbMpobSFWKN3R55jImPPvEiRUj6kCQQD9IA2GRaB6N0m8dnkWnTO3LPj+C+DsgPLa4HC8h9PuaCsc/Ph3qPAHIwv3VJahJlZDm55XnOlEVhmtpB1SwxyXAkEAz0jgxblm9msBp7kaR1ULYujSPwZc11yQSJ5nE2gmobFfNitifF2WsYUTinSyTvY93ujw19kSh+Ztosl31rBX/QJAfw4Xu843PyGBYZgWL8O4sblhQiO0QwJ25GbEL93+Ay1GdsaD8Yxa7zooR32uHjWgF0+Fq3SXojWVrhMypNhLAQJAMZpsB4TlicRzofJewoEsd1/lqCVapELHWElnuzIqRHlQooLhT4eJ3zNMSM7COLkedzBhKhYNJC5VQCZcIikS9QJAJJxgHKZ/K/1BeobAlnh0bzvqNFMtAI2Bu2j4Y/aH3z776HGkxxJ9HQmzRhWLZ5Ac0xo1qRJHy2OmKTmZsOgXmA==
  #绑卡页面
  bindUrl: https://typ.yuehuayueyou.com/allscorepay/bindCard
  #绑卡支付页面
  openCardUrl: https://typ.yuehuayueyou.com/allscorepay/openCardPay

#四方
square:
  merCode: 330100600021
  squarePayUrl: http://118.178.46.246:8080/cashierweb/service/smk/gateway/makeOrder.do
  callbackUrl: https://typ.yuehuayueyou.com/square/callbackApi
  quickPayUrl: http://118.178.46.246:28000/apigate/service/hzsmk/quickpay
  quickCallBackUrl: https://typ.yuehuayueyou.com/squareQuick/callbackApi

#消息队列
mq:
  suffix: _pre_on
  mq_ONSAddr: http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet
  ACCESS_KEY: LTAIp2gpRJI0gvKu
  SECRET_KEY: AfhWdaEw5zrIx9d08Z5058J4QCYEnv